#!/bin/bash

echo "After creating your GitHub repository, run these commands:"
echo ""
echo "# Add all files and commit"
echo "git add ."
echo "git commit -m 'Initial release v1.0.0'"
echo ""
echo "# Add your GitHub repository as remote (replace yourusername with your actual username)"
echo "git remote add origin https://github.com/yourusername/ghclean.git"
echo ""
echo "# Push to GitHub"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "# Create and push a release tag"
echo "git tag v1.0.0"
echo "git push origin v1.0.0"
echo ""
echo "# After pushing, you'll need to:"
echo "# 1. Go to your GitHub repository"
echo "# 2. Click 'Releases' -> 'Create a new release'"
echo "# 3. Choose tag v1.0.0"
echo "# 4. Fill in release notes"
echo "# 5. Publish the release"
echo ""
echo "# Then update the Homebrew formula with:"
echo "# - Your actual GitHub username in the URLs"
echo "# - The SHA256 hash of the release tarball"
